server:
  port: 8080

spring:
    mvc:
      pathmatch:
        matching-strategy: ant-path-matcher

springfox:
  documentation:
    swagger-ui:
      enabled: true

swagger:
  host:
    url: http://localhost:8080
